### ISSUE TITLE
Bug Report: Unsupported installation - docker configuration

### ISSUE THREAD

**Issue by ausfestivus** [home-assistant/supervised-installer#225]
### OS Version

Debian 11.3

### System Information

Linux host 5.10.0-15-arm64 #1 SMP Debian 5.10.120-1 (2022-06-09) aarch64 GNU/Linux

### What happened?

`/config/system_health` is reporting as unsupported.
![Screen Shot 2022-07-15 at 6 21 51 pm](https://user-images.githubusercontent.com/40222285/179184303-cde4aebd-fa6f-49cd-acfe-899255f2677b.png)
Clicking on the **LEARN MORE** button takes me to https://www.home-assistant.io/more-info/unsupported/docker_configuration. The pages says to create the `/etc/docker/daemon.json` file and ensure it contains:
```json
{
    "log-driver": "journald",
    "storage-driver": "overlay2"
}
```

When I view the contents of the file on my rpi4 it contains the correct configuration:
```shell
me@host:~$ sudo cat /etc/docker/daemon.json
{
    "log-driver": "journald",
    "storage-driver": "overlay2"
}
```

The file has no other contents.

### Machine Type

raspberrypi4-64

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by rooferdave** [comment]
Me too!

**Comment by ikifar2012** [comment]
@ausfestivus @rooferdave can you provide me with your docker version?
```
docker -v
```

**Comment by ausfestivus** [comment]
> can you provide me with your docker version?

`Docker version 20.10.17, build 100c701`

**Comment by rooferdave** [comment]
> 

Docker version 20.10.13, build a224086

**Comment by ikifar2012** [comment]
Sorry for the late response, I believe this to be an issue with your cgroup version, please ensure you are running cgroup v1, the installer will do this automatically on an x86_64 machine but on a Pi you will have to do it manually

**Comment by encryptix** [comment]
I started to notice the same error message recently. The supervisor script I used a few months ago has been updated  to include the cgroup command which I was missing. https://github.com/home-assistant/supervised-installer/pull/206

After adding `systemd.unified_cgroup_hierarchy=false` to /boot/cmdline.txt and rebooting I no longer get the warning message.

**Comment by ikifar2012** [comment]
Should be solved in version 1.3.1 https://github.com/home-assistant/supervised-installer/releases/tag/1.3.1, test it and if need be re-open this issue

**Comment by mokkin** [comment]
Please reopen:

I have a fresh install on raspberrypi4-64 with the latest release and still get the warning.
