### ISSUE TITLE
Setup on Debian fails 

### ISSUE THREAD

**Issue by Alberruche** [home-assistant/supervised-installer#286]
### OS Version

Debian GNU/Linux 11 (bullseye)

### System Information

Linux Domotica01 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### What happened?

I'm having an issue installing HA supervised (homeassistant-supervised.deb)

### Machine Type

generic-x86-64

### Installer output

```text
root@Domotica01:~/homeassitant-setup# dpkg -i -D2 ./homeassistant-supervised.deb
(Leyendo la base de datos ... 197078 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar ./homeassistant-supervised.deb ...
D000002: maintscript_fallback nonexistent prerm '/var/lib/dpkg/info/homeassistant-supervised.prerm'
D000002: fork/exec /var/lib/dpkg/tmp.ci/preinst ( upgrade 1.4.2 1.4.2 )
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
Dejando `desviación de /etc/NetworkManager/NetworkManager.conf a /etc/NetworkManager/NetworkManager.conf.real por homeassistant-supervised'
Dejando `desviación de /etc/NetworkManager/system-connections/default a /etc/NetworkManager/system-connections/default.real por homeassistant-supervised'
Dejando `desviación de /etc/docker/daemon.json a /etc/docker/daemon.json.real por homeassistant-supervised'
Dejando `desviación de /etc/network/interfaces a /etc/network/interfaces.real por homeassistant-supervised'
Desempaquetando homeassistant-supervised (1.4.2) sobre (1.4.2) ...
D000002: fork/exec /var/lib/dpkg/info/homeassistant-supervised.postrm ( upgrade 1.4.2 )
D000002: process_archive info installed /var/lib/dpkg/tmp.ci/postinst as /var/lib/dpkg/info/homeassistant-supervised.postinst
D000002: process_archive info unlinked /var/lib/dpkg/info/homeassistant-supervised.md5sums
D000002: process_archive info installed /var/lib/dpkg/tmp.ci/preinst as /var/lib/dpkg/info/homeassistant-supervised.preinst
D000002: process_archive info installed /var/lib/dpkg/tmp.ci/postrm as /var/lib/dpkg/info/homeassistant-supervised.postrm
D000002: process_archive info installed /var/lib/dpkg/tmp.ci/templates as /var/lib/dpkg/info/homeassistant-supervised.templates
D000002: process_archive tmp.ci script/file '..' contains dot
D000002: process_archive tmp.ci script/file '.' contains dot
D000002: process_archive tmp.ci script/file '/var/lib/dpkg/tmp.ci/control' is control
Configurando homeassistant-supervised (1.4.2) ...
D000002: fork/exec /var/lib/dpkg/info/homeassistant-supervised.postinst ( configure  )
[info] Restarting NetworkManager
[info] Set up systemd-journal-gatewayd socket file
[info] Enable systemd-journal-gatewayd
dpkg: error al procesar el paquete homeassistant-supervised (--install):
 el subproceso instalado paquete homeassistant-supervised script post-installation devolvió el código de salida de error 1
Se encontraron errores al procesar:
 homeassistant-supervised
root@Domotica01:~/homeassitant-setup#
```

### Relevant log output

```shell
root@Domotica01:~/homeassitant-setup# journalctl -f
-- Journal begins at Mon 2023-02-13 06:16:55 CET. --
abr 17 07:57:29 Domotica01 NetworkManager[130617]: <info>  [1681711049.2581] device (eno1): Activation: successful, device activated.
abr 17 07:57:29 Domotica01 NetworkManager[130617]: <info>  [1681711049.2618] manager: NetworkManager state is now CONNECTED_GLOBAL
abr 17 07:57:29 Domotica01 NetworkManager[130617]: <info>  [1681711049.2688] manager: (E8:A7:30:5A:55:50): new Bluetooth device (/org/freedesktop/NetworkManager/Devices/9)
abr 17 07:57:29 Domotica01 NetworkManager[130617]: <info>  [1681711049.2699] device (E8:A7:30:5A:55:50): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
abr 17 07:57:29 Domotica01 NetworkManager[130617]: <info>  [1681711049.2723] device (E8:A7:30:5A:55:50): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
abr 17 07:57:29 Domotica01 NetworkManager[130617]: <info>  [1681711049.3344] manager: startup complete
abr 17 07:57:29 Domotica01 systemd[1]: Finished Network Manager Wait Online.
abr 17 07:57:39 Domotica01 systemd[1]: NetworkManager-dispatcher.service: Succeeded.
abr 17 07:57:59 Domotica01 systemd[1]: systemd-hostnamed.service: Succeeded.
abr 17 07:58:10 Domotica01 gnome-shell[1383]: libinput error: event8  - Dell Dell USB Keyboard: client bug: event processing lagging behind by 33ms, your system is too slow
abr 17 07:58:18 Domotica01 NetworkManager[130617]: <info>  [1681711098.8970] manager: (veth45e6999): new Veth device (/org/freedesktop/NetworkManager/Devices/10)
abr 17 07:58:18 Domotica01 kernel: docker0: port 4(vethec211a3) entered blocking state
abr 17 07:58:18 Domotica01 kernel: docker0: port 4(vethec211a3) entered disabled state
abr 17 07:58:18 Domotica01 kernel: device vethec211a3 entered promiscuous mode
abr 17 07:58:18 Domotica01 NetworkManager[130617]: <info>  [1681711098.8981] manager: (vethec211a3): new Veth device (/org/freedesktop/NetworkManager/Devices/11)
abr 17 07:58:18 Domotica01 systemd-udevd[130657]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
abr 17 07:58:18 Domotica01 systemd-udevd[130657]: Using default interface naming scheme 'v247'.
abr 17 07:58:18 Domotica01 systemd-udevd[130656]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
abr 17 07:58:18 Domotica01 systemd-udevd[130656]: Using default interface naming scheme 'v247'.
abr 17 07:58:19 Domotica01 containerd[634]: time="2023-04-17T07:58:19.553667725+02:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
abr 17 07:58:19 Domotica01 containerd[634]: time="2023-04-17T07:58:19.553811783+02:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
abr 17 07:58:19 Domotica01 containerd[634]: time="2023-04-17T07:58:19.553848345+02:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
abr 17 07:58:19 Domotica01 containerd[634]: time="2023-04-17T07:58:19.554286061+02:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/71560c8b452654985bdaf1c3c6ec27bc022904025ca5ffe776eec1217ba307ed pid=130686 runtime=io.containerd.runc.v2
abr 17 07:58:19 Domotica01 systemd[1]: run-docker-runtime\x2drunc-moby-71560c8b452654985bdaf1c3c6ec27bc022904025ca5ffe776eec1217ba307ed-runc.A15Zou.mount: Succeeded.
abr 17 07:58:19 Domotica01 systemd[688]: run-docker-runtime\x2drunc-moby-71560c8b452654985bdaf1c3c6ec27bc022904025ca5ffe776eec1217ba307ed-runc.A15Zou.mount: Succeeded.
abr 17 07:58:19 Domotica01 kernel: new mount options do not match the existing superblock, will be ignored
abr 17 07:58:19 Domotica01 kernel: eth0: renamed from veth45e6999
abr 17 07:58:19 Domotica01 kernel: docker0: port 4(vethec211a3) entered blocking state
abr 17 07:58:19 Domotica01 kernel: docker0: port 4(vethec211a3) entered forwarding state
abr 17 07:58:19 Domotica01 NetworkManager[130617]: <info>  [1681711099.7829] device (vethec211a3): carrier: link connected
abr 17 07:58:19 Domotica01 gnome-shell[1383]: Removing a network device that was not added
abr 17 07:58:20 Domotica01 containerd[634]: time="2023-04-17T07:58:20.423793552+02:00" level=info msg="shim disconnected" id=71560c8b452654985bdaf1c3c6ec27bc022904025ca5ffe776eec1217ba307ed
abr 17 07:58:20 Domotica01 containerd[634]: time="2023-04-17T07:58:20.423840640+02:00" level=warning msg="cleaning up after shim disconnected" id=71560c8b452654985bdaf1c3c6ec27bc022904025ca5ffe776eec1217ba307ed namespace=moby
abr 17 07:58:20 Domotica01 containerd[634]: time="2023-04-17T07:58:20.423851386+02:00" level=info msg="cleaning up dead shim"
abr 17 07:58:20 Domotica01 dockerd[806]: time="2023-04-17T07:58:20.423838503+02:00" level=info msg="ignoring event" container=71560c8b452654985bdaf1c3c6ec27bc022904025ca5ffe776eec1217ba307ed module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
abr 17 07:58:20 Domotica01 containerd[634]: time="2023-04-17T07:58:20.431108442+02:00" level=warning msg="cleanup warnings time=\"2023-04-17T07:58:20+02:00\" level=info msg=\"starting signal loop\" namespace=moby pid=130752 runtime=io.containerd.runc.v2\n"
abr 17 07:58:20 Domotica01 kernel: docker0: port 4(vethec211a3) entered disabled state
abr 17 07:58:20 Domotica01 kernel: veth45e6999: renamed from eth0
abr 17 07:58:20 Domotica01 systemd-udevd[130657]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
abr 17 07:58:20 Domotica01 NetworkManager[130617]: <info>  [1681711100.5492] manager: (veth45e6999): new Veth device (/org/freedesktop/NetworkManager/Devices/12)
abr 17 07:58:20 Domotica01 systemd-udevd[130657]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
abr 17 07:58:20 Domotica01 kernel: docker0: port 4(vethec211a3) entered disabled state
abr 17 07:58:20 Domotica01 kernel: device vethec211a3 left promiscuous mode
abr 17 07:58:20 Domotica01 kernel: docker0: port 4(vethec211a3) entered disabled state
abr 17 07:58:20 Domotica01 NetworkManager[130617]: <info>  [1681711100.6989] device (vethec211a3): released from master device docker0
abr 17 07:58:20 Domotica01 gnome-shell[1383]: Removing a network device that was not added
abr 17 07:58:20 Domotica01 gnome-shell[1383]: Removing a network device that was not added
abr 17 07:58:20 Domotica01 systemd[688]: run-docker-netns-5fb5fc4b4169.mount: Succeeded.
abr 17 07:58:20 Domotica01 systemd[1]: run-docker-netns-5fb5fc4b4169.mount: Succeeded.
abr 17 07:58:20 Domotica01 systemd[1]: var-lib-docker-overlay2-ab1758ac303f28ddd44302deead0c75eb49ced02e24faaa4cee7625eb5e5ae76-merged.mount: Succeeded.
abr 17 07:58:20 Domotica01 systemd[688]: var-lib-docker-overlay2-ab1758ac303f28ddd44302deead0c75eb49ced02e24faaa4cee7625eb5e5ae76-merged.mount: Succeeded.
abr 17 07:58:25 Domotica01 rtkit-daemon[864]: Supervising 7 threads of 4 processes of 1 users.
abr 17 07:58:25 Domotica01 rtkit-daemon[864]: Supervising 7 threads of 4 processes of 1 users.
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by mjbogusz** [comment]
I've encountered the same problem.

But for me this broke an existing, working installation - when trying to debug the journald-gateway "unsupported" state (which I've already fixed half a year ago, but it showed up again...), I tried updating `homeassistant-supervised` and due to this bug this has left my system in not-uninstalled not-installed limbo.

The workaround was to remove the package, download the previous release (1.4.1) and install that instead:
```sh
sudo apt remove -y homeassistant-supervised
wget https://github.com/home-assistant/supervised-installer/releases/download/1.4.1/homeassistant-supervised.deb -O homeassistant-supervised-1.4.1.deb
sudo apt install -y ./homeassistant-supervised-1.4.1.deb
```

I wish there was an error message in addition to the "exit 1" somewhere in the middle of the setup script - as it is now there is no indication as to what causes the error, no message in logs and no easily googlable error code.

<details><summary>Full output from journal during `apt -f install`</summary>
<p>

```sh
May 03 21:55:22 hass sudo[2941]:     hass : TTY=pts/0 ; PWD=/home/hass ; USER=root ; COMMAND=/usr/bin/apt -f install
May 03 21:55:22 hass sudo[2941]: pam_unix(sudo:session): session opened for user root(uid=0) by hass(uid=1000)
May 03 21:55:23 hass systemd[1]: NetworkManager-wait-online.service: Succeeded.
May 03 21:55:23 hass systemd[1]: Stopped Network Manager Wait Online.
May 03 21:55:23 hass systemd[1]: Stopping Network Manager Wait Online...
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.3477] caught SIGTERM, shutting down normally.
May 03 21:55:23 hass systemd[1]: Stopping Network Manager...
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.3754] dhcp4 (enp0s31f6): canceled DHCP transaction
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.3755] dhcp4 (enp0s31f6): state changed bound -> terminated
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.3760] manager: NetworkManager state is now CONNECTED_SITE
May 03 21:55:23 hass dbus-daemon[501]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.62' (uid=0 pid=2683 comm="/usr/sbin/NetworkManager --no-daemon ")
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.3790] device (wlp2s0): state change: disconnected -> unmanaged (reason 'unmanaged', sys-iface-state: 'managed')
May 03 21:55:23 hass wpa_supplicant[516]: nl80211: deinit ifname=p2p-dev-wlp2s0 disabled_11b_rates=0
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.4100] device (p2p-dev-wlp2s0): state change: disconnected -> unmanaged (reason 'removed', sys-iface-state: 'removed')
May 03 21:55:23 hass systemd[1]: Starting Network Manager Script Dispatcher Service...
May 03 21:55:23 hass NetworkManager[2683]: <info>  [1683143723.4267] exiting (success)
May 03 21:55:23 hass dbus-daemon[501]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
May 03 21:55:23 hass systemd[1]: NetworkManager.service: Succeeded.
May 03 21:55:23 hass systemd[1]: Stopped Network Manager.
May 03 21:55:23 hass systemd[1]: Started Network Manager Script Dispatcher Service.
May 03 21:55:23 hass systemd[1]: Starting Network Manager...
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.4599] NetworkManager (version 1.30.6) is starting... (after a restart)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.4600] Read config: /etc/NetworkManager/NetworkManager.conf (lib: no-mac-addr-change.conf)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.4616] bus-manager: acquired D-Bus service "org.freedesktop.NetworkManager"
May 03 21:55:23 hass systemd[1]: Started Network Manager.
May 03 21:55:23 hass systemd[1]: Starting Network Manager Wait Online...
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.4901] manager[0x557cb466e030]: monitoring kernel firmware directory '/lib/firmware'.
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.4902] monitoring ifupdown state file '/run/network/ifstate'.
May 03 21:55:23 hass dbus-daemon[501]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.74' (uid=0 pid=2973 comm="/usr/sbin/NetworkManager --no-daemon ")
May 03 21:55:23 hass systemd[1]: Starting Hostname Service...
May 03 21:55:23 hass wpa_supplicant[516]: nl80211: deinit ifname=wlp2s0 disabled_11b_rates=0
May 03 21:55:23 hass dbus-daemon[501]: [system] Successfully activated service 'org.freedesktop.hostname1'
May 03 21:55:23 hass systemd[1]: Started Hostname Service.
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5470] hostname: hostname: using hostnamed
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5471] hostname: hostname changed from (none) to "hass"
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5479] dns-mgr[0x557cb4658170]: init: dns=default,systemd-resolved rc-manager=file
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5489] rfkill0: found Wi-Fi radio killswitch (at /sys/devices/pci0000:00/0000:00:1d.0/0000:02:00.0/ieee80211/phy0/rfkill0) (driver iwlwifi)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5491] manager[0x557cb466e030]: rfkill: Wi-Fi hardware radio set enabled
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5491] manager[0x557cb466e030]: rfkill: WWAN hardware radio set enabled
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5500] Loaded device plugin: NMWifiFactory (/usr/lib/x86_64-linux-gnu/NetworkManager/1.30.6/libnm-device-plugin-wifi.so)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5502] Loaded device plugin: NMAtmManager (/usr/lib/x86_64-linux-gnu/NetworkManager/1.30.6/libnm-device-plugin-adsl.so)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5510] Loaded device plugin: NMTeamFactory (/usr/lib/x86_64-linux-gnu/NetworkManager/1.30.6/libnm-device-plugin-team.so)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5526] Loaded device plugin: NMWwanFactory (/usr/lib/x86_64-linux-gnu/NetworkManager/1.30.6/libnm-device-plugin-wwan.so)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5530] Loaded device plugin: NMBluezManager (/usr/lib/x86_64-linux-gnu/NetworkManager/1.30.6/libnm-device-plugin-bluetooth.so)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5532] manager: rfkill: Wi-Fi enabled by radio killswitch; enabled by state file
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5533] manager: rfkill: WWAN enabled by radio killswitch; enabled by state file
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5534] manager: Networking is enabled by state file
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5534] dhcp-init: Using DHCP client 'internal'
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5535] settings: Loaded settings plugin: keyfile (internal)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5562] device (lo): carrier: link connected
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5564] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5569] manager: (docker0): new Bridge device (/org/freedesktop/NetworkManager/Devices/2)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5573] device (enp0s31f6): carrier: link connected
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5576] manager: (enp0s31f6): new Ethernet device (/org/freedesktop/NetworkManager/Devices/3)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5584] manager: (enp0s31f6): assume: will attempt to assume matching connection 'Supervisor enp0s31f6' (dc515952-289f-4fc1-b838-6e29a98ef3a2) (indicated)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5584] device (enp0s31f6): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5591] device (enp0s31f6): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5598] device (enp0s31f6): Activation: starting connection 'Supervisor enp0s31f6' (dc515952-289f-4fc1-b838-6e29a98ef3a2)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5602] manager: (hassio): new Bridge device (/org/freedesktop/NetworkManager/Devices/4)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5608] manager: (wg0): new WireGuard device (/org/freedesktop/NetworkManager/Devices/5)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5614] device (wg0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5618] device (wg0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5622] device (wg0): Activation: starting connection 'wg0' (e2e396f4-d141-42ae-9295-d1fdefddaed6)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5623] device (wlp2s0): driver supports Access Point (AP) mode
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5628] manager: (wlp2s0): new 802.11 Wi-Fi device (/org/freedesktop/NetworkManager/Devices/6)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.5633] device (wlp2s0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
May 03 21:55:23 hass sudo[2941]: pam_unix(sudo:session): session closed for user root
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8221] device (enp0s31f6): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8229] device (enp0s31f6): state change: prepare -> config (reason 'none', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8259] device (wg0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8266] device (wg0): state change: prepare -> config (reason 'none', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8394] device (wg0): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8398] device (wg0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8413] device (enp0s31f6): state change: config -> ip-config (reason 'none', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8418] dhcp4 (enp0s31f6): activation: beginning transaction (timeout in 45 seconds)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8432] device (enp0s31f6): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8489] dhcp4 (enp0s31f6): state changed unknown -> bound, address=10.0.0.20
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8495] device (wg0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8509] device (enp0s31f6): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8515] device (wg0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8519] manager: NetworkManager state is now CONNECTED_LOCAL
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8528] policy: set 'Supervisor enp0s31f6' (enp0s31f6) as default for IPv4 routing and DNS
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8565] device (wg0): Activation: successful, device activated.
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8570] device (enp0s31f6): state change: secondaries -> activated (reason 'none', sys-iface-state: 'assume')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8576] manager: NetworkManager state is now CONNECTED_SITE
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8583] device (enp0s31f6): Activation: successful, device activated.
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8648] manager: NetworkManager state is now CONNECTED_GLOBAL
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8914] device (wlp2s0): supplicant interface state: internal-starting -> disconnected
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8914] Wi-Fi P2P device controlled by interface wlp2s0 created
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8916] manager: (p2p-dev-wlp2s0): new 802.11 Wi-Fi P2P device (/org/freedesktop/NetworkManager/Devices/7)
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8918] device (p2p-dev-wlp2s0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8922] device (wlp2s0): state change: unavailable -> disconnected (reason 'supplicant-available', sys-iface-state: 'managed')
May 03 21:55:23 hass NetworkManager[2973]: <info>  [1683143723.8927] device (p2p-dev-wlp2s0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
May 03 21:55:23 hass NetworkManager[2973]: <warn>  [1683143723.8931] sup-iface[c4da2c979152e1cb,7,wlp2s0]: call-p2p-cancel: failed with P2P cancel failed
May 03 21:55:27 hass wpa_supplicant[516]: wlp2s0: CTRL-EVENT-REGDOM-CHANGE init=DRIVER type=COUNTRY alpha2=EU
May 03 21:55:27 hass NetworkManager[2973]: <info>  [1683143727.1033] manager: startup complete
May 03 21:55:27 hass systemd[1]: Finished Network Manager Wait Online.
```
</p>
</details>

**Comment by mabusdogma** [comment]
Struggling for hours! You made my day!

```
sudo apt remove -y homeassistant-supervised
wget https://github.com/home-assistant/supervised-installer/releases/download/1.4.1/homeassistant-supervised.deb -O homeassistant-supervised-1.4.1.deb
sudo apt install -y ./homeassistant-supervised-1.4.1.deb
```

**Comment by yevon** [comment]
Same error here with ubuntu 22.04, but downgrading to 1.4.1 does not fix the issue for me

**Comment by ffries** [comment]
I can confirm that installing under Debian 12.1 works except that systemd-resolved does not point to any DNS server.

**Comment by mjbogusz** [comment]
After upgrading my base system to Debian 12 I've hit an issue looking identically to this one again...

This time it was the `systemd-journal-gatewayd.socket` systemd unit not existing. To fix that:
```sh
sudo apt install --reinstall systemd-journal-remote
```

Oh, and also I had to set the DNS server as per https://github.com/home-assistant/supervised-installer/issues/304.

The main issue here is that the post-installation script is very fragile, handles only the very happy path and doesn't correctly report errors - here [this line](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst#L45) was failing but the error message was redirected to `/dev/null`...

---

For future reference, debugging the postinst script (based on [this SE question on editing postinst](https://unix.stackexchange.com/questions/138188/easily-unpack-deb-edit-postinst-and-repack-deb)):
```sh
# Get the latest homeassistant-supervised
wget -O homeassistant-supervised.deb https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
# Unpack the deb
mkdir hass-sv
dpkg-deb -R homeassistant-supervised.deb hass-sv
# open the postinst script - try running the suspected problem lines manually
nano hass-sv/DEBIAN/postinst
```
For modifying the script and repacking the deb with modifications:
```sh
fakeroot sh -c '
  mkdir hass-sv;
  dpkg-deb -R homeassistant-supervised.deb hass-sv;
  nano hass-sv/DEBIAN/postinst;
  dpkg-deb -b hass-sv homeassistant-supervised-fix.deb
'
```
(replace nano with your choice of editor)

**Comment by mjbogusz** [comment]
But wait, there's more!

After the update the supervisor started complaining that it's "not privileged". The issue card only links to a BS page describing neither the issue nor any real solutions - the supervisor container WAS running in the privileged mode, but it had some weird issues accessing udev (logs entry: `Not privileged to run udev monitor!`).

Here's a solution, based on [this old discussion](https://github.com/home-assistant/supervisor/issues/2351#issuecomment-739890258):
```sh
docker container rm -f hassio_supervisor
sudo systemctl restart hassio-supervisor.service
```

I feel that absolutely no one tests any upgrade path for HASupervised, as it's yet another situation where it breaks because of it's own previous versions' actions...

**Comment by Lockszmith-GH** [comment]
@mjbogusz I think you are absolutly right - no real testing is done, as this is the method nabucasa was sort-of forced into maintaining inspite of their choice.

At least we have a good community here with detailed bug reports. We'll do the testing. I'm guessing if you PR this, they will approve it.

**Comment by ikifar2012** [comment]
> I can confirm that installing under Debian 12.1 works except that systemd-resolved does not point to any DNS server.

are you using a static DNS or DHCP provided DNS?

**Comment by ikifar2012** [comment]
> But wait, there's more!
> 
> After the update the supervisor started complaining that it's "not privileged". The issue card only links to a BS page describing neither the issue nor any real solutions - the supervisor container WAS running in the privileged mode, but it had some weird issues accessing udev (logs entry: `Not privileged to run udev monitor!`; extracted by running `docker logs hassio_supervisor`).
> 
> Here's a solution, based on [this old discussion](https://github.com/home-assistant/supervisor/issues/2351#issuecomment-739890258):
> 
> ```shell
> docker container rm -f hassio_supervisor
> sudo systemctl restart hassio-supervisor.service
> ```
> 
> I feel that absolutely no one tests any upgrade path for HASupervised, as it's yet another situation where it breaks because of it's own previous versions' actions...

In trying to solve this I discovered a very strange issue, after the container is destroyed on recreation it displays the error, once the container is started if I restart it again a second time the error message disappears, currently trying to figure out the root cause... if anyone has some insight into what could be causing this let me know
